name: ktwelchsample
favicon: null
layout_spectrum: 0.43959624064154923
typography_spectrum: 0.683896774193272
title: 'Adventures in personal growth, productivity, and entrepreneurship'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2e0d4'
    - '#94918a'
    - '#54727d'
    - '#333939'
    - '#1f2324'
  brandStrength: 0.5
  lightness: 0.6543565611355007
  saturation: 0.006481735734269023
  rhythmicContrast: 0.40376800834201276
purpose: []
